import "./src/assets/styles/style-2020.css"
// import "./src/assets/styles/style-rtl.css"
import "./src/assets/styles/print.css"
import "./src/assets/styles/style-php.css"
import "./src/assets/styles/style-site.css"
import "./src/assets/styles/globals.css"
